[sources.log_in]
type = "file"
ignore_older_secs = 86400
include = [ "/log/*.log" ]
read_from = "beginning"

[sinks.loki]
type = "loki"
inputs = [ "log_in" ]
endpoint = "http://loki:3100"
encoding.codec = "json"
labels.key = "value" # example
labels.key = "{{ event_field }}" # example